### ISSUE TITLE
Breaking changes in 1.6.1

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_resources#10]
Howdy 👋 

I updated to the latest 1.6.1 and ran the test suite and I noticed that a couple of my datatables were failing to render, with the same error. Then tested against each commit since 1.5.5 and I tracked down the error to a commit. Something breaks datatables in this commit:

https://github.com/code-and-effect/effective_resources/commit/e74a525bcc71297f79f8ec154c10b786a3b30371

I get this error:

<img width="1626" alt="Captura de pantalla 2020-11-21 a las 12 12 09" src="https://user-images.githubusercontent.com/259568/99875878-1b4cd700-2bf3-11eb-81d0-25947d9db814.png">

I only get the error in effective datatables in which there is a column in which I use the `_id` form instead of the `contact` form. For example:

````
module ManagerPanel
  class ResourcesDatatable < Effective::Datatable
    datatable do
        col :contact_id do |t| 
            'hello'
        end
    end
   
    collection do
      ...
    end 
  end
end
````
 
That will give me the error. But if I use `col :contact` instead then it is fine. Searching and sorting works fine too.

Is this an intended change? Should I not use `_id` form ?

Thanks!

**Comment by Nerian** [comment]
More info:  It only fails if the effective datatable is being rendered from a controller inside an engine. 

If I render the datatable from a controller that is not part of an engine then it works fine; even if the effective datatable itself is namespaced inside an engine.

**Comment by matt-riemer** [comment]
Hey Nerian,

sorry this change affected you. The whole point of these 1.6.x updates is to get the resources and datatable working better inside a rails engine

I've got 3 rails engines I'm building soon, and I want the datatables `actions_col` to just work.  Which is based on the routes.

https://github.com/code-and-effect/effective_resources/blob/master/app/models/effective/resources/actions.rb#L25

Is the current code.  In this changes, I added the "for each Rails::Engine.subclass also look at all the routes" and this must be causing some unintended consequence

I would not have expected this to affect the contact_id type columns in this way :)

when I write my datatables, I use `col :contact` not `:contact_id` but both should work.

I'll try to reproduce on Monday or early this week and get both working again.

Thanks!

**Comment by Nerian** [comment]
No problem, I changed the columns to use the form that works and all it's fine. No rush.

I noticed that bug still happens even if in tables without action_cols. So I assume the `routes` code gets executed always.

In my app I am using multiple engines, and I have been using effective datatable without issues. I don't use the auto-generated `action_cols`. I always use a custom partial because I need translations, and sometimes custom parameters. Like this:

```
actions_col partial: 'datatables/manager_panel/charges/controls'
```

And the partial look like this (Slim code template)

```slim
ruby:
  if datatable.attributes[:invoice_id]
    back_to = manager_panel.invoice_path(current_account, datatable.attributes[:invoice_id], anchor: 'charges')
  elsif datatable.attributes[:member_id]
    back_to = manager_panel.contact_path(current_account, datatable.attributes[:member_id], anchor: 'charges')
  else
    back_to = manager_panel.charges_path(current_account)
  end

= dropdown split: true, btn_class: 'btn-outline-dark', right: true
  = dropdown_link_to t('general.show'), manager_panel.charge_path(current_account, resource), class: 'btn btn-outline-dark'
  = dropdown_link_to t('general.remove'), manager_panel.charge_path(current_account, resource, back_to: back_to), method: :delete, 'data-confirm' => t('general.confirm_delete_charge')
```
Notice that I have to prepend the engine name to the route helper, otherwise it errors out when getting sorting/searching/filtering. `manager_panel.invoice_path`. Maybe this could useful to the refactor you are doing.

**Comment by matt-riemer** [comment]
Hey, so I dug into this a bit more, using a datatable inside and outside a rails engine

I wasn't able to replicate your error, but I did release effective_resources 1.6.2 to better handle/rescue from it. I think this will prevent any further errors going forward! :)

So then,

When I do`col :user` the datatable picks it up as an `as: :belongs_to` column type and tries to render it with an edit or show action link.  If I can visit "/users/123/edit" the datatable will automatically try to link there.

You can disable the link entirely by doing `col :user, action: false` or `col :user, action: :show`.

I tried to reproduce your error with `col :user_id` but it just didn't raise the error. It didn't run the linking code for me at all.

https://github.com/code-and-effect/effective_logging/blob/master/app/datatables/effective_logs_datatable.rb#L13

I'm going to keep an eye on this in the future

**Comment by Nerian** [comment]
I can confirm the issue no longer happens with 1.6.2. Nicely done 👍
