### ISSUE TITLE
NameError: uninitialized constant EffectiveResources::Engine::ActsAsArchived

### ISSUE THREAD

**Issue by flenny** [code-and-effect/effective_resources#13]
When running Rails (7.0.2.3) application using _effective_resources_ (1.15.1) I get the following error:
```
NameError: uninitialized constant EffectiveResources::Engine::ActsAsArchived
        ActiveRecord::Base.extend(ActsAsArchived::Base)
                                  ^^^^^^^^^^^^^^
/usr/local/bundle/gems/effective_resources-1.15.1/lib/effective_resources/engine.rb:25:in `block (2 levels) in <class:Engine>'
```
The application is running just fine if I add some `require` statements in _engine.rb_ for `app/models/concerns/*.rb` files or if I switch back to the latest Rails 6 release.
Maybe this has something to do with the newly integrated zeitwerk? I tried several versions of _effective_resources_. Still the same behavior. How do I get arround this error?

Thank you in advance for your support!

**Comment by matt-riemer** [comment]
Hey flenny!

Sorry friend, I haven't approached a rails 7 project yet, or tested any of the effective_* gems on it.

I'm sure it's just some small change to properly include these concerns, but it looks like the way active record concerns are loaded differs in rails 6 vs 7.

**Comment by matt-riemer** [comment]
Hey again @flenny

The latest version of effective_resources 1.16.0 is working with rails 7!

The rails server should boot without any deprecations, warnings or errors.

I have a small demo app with the latest rails 7, but still the laughably old jQuery and Twitter Bootstrap 4 demonstrating the latest effective_datatables and effective_resources:

https://github.com/code-and-effect/effective_datatables_demo

Have a kickass day :)

**Comment by Nerian** [comment]
I get the same error. https://github.com/code-and-effect/effective_resources/issues/14 In my case I tracked it down to using Sorcery. Did you manage to solve it @flenny ?

**Comment by flenny** [comment]
No @Nerian. Unfortunately not.

I patched _effective_resources_ `engine.rb` for myself, because I thought the problem is related to my code/app. In my case all the [ActsAs...](https://github.com/code-and-effect/effective_resources/blob/cbea0c14b8c64dfcd44ecaf43bf2317eb6d148d5/lib/effective_resources/engine.rb#L25-L32) cannot be found if I `rails c`/`rails s` or `rake db:setup` the app. If I `require` all the concerns in _app/models/concerns_ folder explicitly everything is fine. I'm not really deep into this Rails 7 new _Zeitwek_ thing, but I guess there could be an issue with the naming and/or folder structure of these nested _ActsAs..._ concerns. Maybe there must be a subfolder _ActsAs..._ in _/app/models/concerns/_ and then a _.rb_ file with the most inner module name in it? IMHO _/app/controllers/concerns_ and _/app/models/concerns_ should be autoloaded automatically. Therefore I do not understand this [line](https://github.com/code-and-effect/effective_resources/blob/cbea0c14b8c64dfcd44ecaf43bf2317eb6d148d5/lib/effective_resources/engine.rb#L8).

@matt-riemer There is this `bin/rails zeitwerk:check` tool built in into Rails 7. Maybe there are some additional hints.

Thanks a lot @matt-riemer for your support!

**Comment by matt-riemer** [comment]
Give 1.17.1 a shot, might just work properly now :)
