### ISSUE TITLE
Admin namespace

### ISSUE THREAD

**Issue by Nerian** [code-and-effect/effective_resources#15]
Hi,

I get the following error:

```
expected no Exception, got #<TypeError: Admin is not a module
       /Users/Nerian/satchel/show-app/backend/shared/gems/smhw-business-logic/app/models/admin.rb:1: previous definition of Admin was here> with backtrace:
         # /Users/Nerian/.rvm/gems/ruby-3.1.2/gems/effective_resources-1.18.5/app/controllers/admin/select2_ajax_controller.rb:1:in `<main>'
```

This happens because of this controller:
https://github.com/code-and-effect/effective_resources/blob/master/app/controllers/admin/select2_ajax_controller.rb

It defines the `Admin` module. This conflicts with one of my classes which is called `class Admin`.Perhaps this controller should use the EffectiveResources namespace in order to avoid conflicts.

**Comment by Nerian** [comment]
Using 1.18.0 works fine.

**Comment by matt-riemer** [comment]
Hey Nerian!

I'm on vacation this week but will crush this in a weeks time or so.

Stick on that old version, sorry for any name conflicts :(

**Comment by Nerian** [comment]
No problem, thanks! 👍
