### ISSUE TITLE
respond_to ?

### ISSUE THREAD

**Issue by rbosch** [code-and-effect/effective_resources#5]
Hi!

Do you have any idea how I can get the respond_to to work?  

I registered some extra mime_types, but i'm getting the following error: 
`Mime::Type.register "text/zpl", :zpl`

`xxxController#show is missing a template for this request format and variant. request.formats: ["text/zpl"] request.variant: []`

And I want to open 
`http://hostname/controller/1234.zpl`

Its unclear which file its looking for from the error message. 

Actually in my case, I also need to **set a different layout** for this mime (zpl is a sticker label).

**Comment by matt-riemer** [comment]
Hey @rbosch 

Yea, you're gonna need to write a custom controller method.  effective_resources won't do this automatically for you.

Are you just tryin' to do a show action?

How about something like

```ruby
  def show
    @thing = Thing.find(params[:id])
    authorize! :show, @thing

    respond_to do |format|
      format.html do
        render 'thing'   # Regular html rails partial

        # Or maybe just redirect?
        # redirect_to thing_path(format: 'zpl:)
      end

      format.zpl do
         # Render your zpl. Probably some kind of render or class method?
         render body: @thing.to_zpl
      end
    end
  end
```
