### ISSUE TITLE
path = resource.action_path(:new)).present? not working for controllers with _ in the name

### ISSUE THREAD

**Issue by rbosch** [code-and-effect/effective_resources#6]
Hi,

I have a few (camelized) controllers like: ProjectOrders (project_orders).  These have normal routes like: 

```
/project_orders/new
/project_orders/1/edit
```

In the index template there is a check to see if the route exists for the current controller.

```
if .... && (path = resource.action_path(:new)).present? 

```

The **resource.action_path(:new)).present?** returns a empty path. While the path **does** exists.

I had a look in the **actions.rb**, I assume something goes wrong in the routes matching. Perticalular in the **def routes** method

Any idea?

Thanks!

**Comment by matt-riemer** [comment]
Hmm great question!

Are you using `resources :project_orders` in your routes?  I'd be curious to use `binding.pry` and step through the action_path helper see what's tripping it up

I think that the problem is probably isolated in that one method -- might be easy to debug :)

You can always check out a gem locally

`git clone github.com/code-and-effect/effective_resources.git`

and then use it locally

`gem 'effective_resources', path: '~/Sites/effective_resources'`

and then `bundle`

Then you can use regular debugging practices to look at that `action_path` method and see which line is doing incorrect :)

**Comment by rbosch** [comment]
Hi Matt,

Yes i have it in my routes, it just shows up.

Its just in the index page, to create a 'New Project Order' button. So it trips on:

```resource.action_path(:new)```


```
                // rake routes | grep project_orders

                lookup_project_order GET    /project_orders/:id/lookup(.:format)                                     project_orders#lookup
                            import_project_order POST   /project_orders/:id/import(.:format)                                     project_orders#import
                                  project_orders GET    /project_orders(.:format)                                                project_orders#index
                                                 POST   /project_orders(.:format)                                                project_orders#create
                               new_project_order GET    /project_orders/new(.:format)                                            project_orders#new
                              edit_project_order GET    /project_orders/:id/edit(.:format)                                       project_orders#edit
                                   project_order GET    /project_orders/:id(.:format)                                            project_orders#show
                                                 PATCH  /project_orders/:id(.:format)                                            project_orders#update
                                                 PUT    /project_orders/:id(.:format)                                            project_orders#update
                                                 DELETE /project_orders/:id(.:format)                                            project_orders#destroy
```
Awesome tip. I will try that.

**Comment by rbosch** [comment]
Hi Matt,

Mystery solved. Well I guess. It has nothing todo with **CamelCase** names, but apparently with the **order** in which you name the **controllers** and the nesting in the **route file**. I tried debugging your code, but it got somewhat complex.  The controller should be **first** named in nested form, and last as non nested. Beats me.

_I ended up with creating a new test_test controller to see if that would work, that did. Then I was guessing it had to be something in the routes order._

```
# what does NOT work in routes.rb
resources :project_orders
resources :something_else do
  resources :project_orders
end

# what does work in routes.rb
resources :something_else do
  resources :project_orders
end
resources :project_orders
```

**Comment by matt-riemer** [comment]
great investigation, thanks @rbosch !!
